/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ComoComprarRouteImport } from './routes/como-comprar'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as TrocaEDevolucoesRouteImport } from './routes/troca-e-devolucoes'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoComprarRoute = ComoComprarRouteImport.update({
  id: '/como-comprar',
  path: '/como-comprar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocaEDevolucoesRoute = TrocaEDevolucoesRouteImport.update({
  id: '/troca-e-devolucoes',
  path: '/troca-e-devolucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/como-comprar': typeof ComoComprarRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/troca-e-devolucoes': typeof TrocaEDevolucoesRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/como-comprar': typeof ComoComprarRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/troca-e-devolucoes': typeof TrocaEDevolucoesRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/como-comprar': typeof ComoComprarRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/troca-e-devolucoes': typeof TrocaEDevolucoesRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/como-comprar'
    | '/contato'
    | '/produtos'
    | '/quem-somos'
    | '/troca-e-devolucoes'
    | '/api/public/mercadopago-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/como-comprar'
    | '/contato'
    | '/produtos'
    | '/quem-somos'
    | '/troca-e-devolucoes'
    | '/api/public/mercadopago-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/como-comprar'
    | '/contato'
    | '/produtos'
    | '/quem-somos'
    | '/troca-e-devolucoes'
    | '/api/public/mercadopago-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  ComoComprarRoute: typeof ComoComprarRoute
  ContatoRoute: typeof ContatoRoute
  ProdutosRoute: typeof ProdutosRoute
  QuemSomosRoute: typeof QuemSomosRoute
  TrocaEDevolucoesRoute: typeof TrocaEDevolucoesRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-comprar': {
      id: '/como-comprar'
      path: '/como-comprar'
      fullPath: '/como-comprar'
      preLoaderRoute: typeof ComoComprarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/troca-e-devolucoes': {
      id: '/troca-e-devolucoes'
      path: '/troca-e-devolucoes'
      fullPath: '/troca-e-devolucoes'
      preLoaderRoute: typeof TrocaEDevolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  ComoComprarRoute: ComoComprarRoute,
  ContatoRoute: ContatoRoute,
  ProdutosRoute: ProdutosRoute,
  QuemSomosRoute: QuemSomosRoute,
  TrocaEDevolucoesRoute: TrocaEDevolucoesRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
